### PR TITLE
Make them colour by default in the preview

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by peternewman** [comment]
Thanks @maxdow .

**Comment by peternewman** [comment]
You should turn on GitHub pages @maxdow (see here and choose Project site https://pages.github.com/ ), then people could see a preview here:
https://maxdow.github.io/skycons/

**Comment by maxdow** [comment]
Thanks that's a good suggestion I will do this

**Comment by maxdow** [comment]
Done ;)

**Comment by peternewman** [comment]
> Done ;)

Great, this PR makes use of that fact:
https://github.com/maxdow/skycons/pull/4

**Pull request merged**
